/*
 * Copyright 2026 ECSDevs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 */

package cc.ptoe.messenger.presentation.terminal

/** A color specification for a terminal cell. */
sealed interface TerminalColor {
    /** No explicit color: use the terminal's default palette. */
    data object Default : TerminalColor

    /** Indexed color, one of the 256 ANSI/xterm palette entries (0..255). */
    data class Index(val value: Int) : TerminalColor

    /** 24-bit RGB color, each component in 0..255. */
    data class Truecolor(val red: Int, val green: Int, val blue: Int) : TerminalColor
}

/** Character attributes applied to a [TerminalCell]. */
data class TerminalAttrs(
    val fg: TerminalColor = TerminalColor.Default,
    val bg: TerminalColor = TerminalColor.Default,
    val bold: Boolean = false,
    val dim: Boolean = false,
    val italic: Boolean = false,
    val underline: Boolean = false,
    val blink: Boolean = false,
    val inverse: Boolean = false,
    val strike: Boolean = false,
    val hide: Boolean = false,
) {
    companion object {
        /** The default attribute set: no styling, default colors. */
        val DEFAULT: TerminalAttrs = TerminalAttrs()
    }
}

/** A single character cell in the terminal grid. */
data class TerminalCell(val char: Char, val attrs: TerminalAttrs)

/**
 * Snapshot of the terminal screen.
 *
 * @property grid grid[row][col]; every row has exactly [cols] cells.
 * @property cursorRow zero-based cursor row.
 * @property cursorCol zero-based cursor column.
 * @property cursorVisible whether the cursor is currently visible.
 * @property reverseVideo global inverse-video mode (DECSCNM, private mode 5).
 * @property title the last window title set via OSC 0 or 2.
 * @property scrollback older rows that scrolled off the top of the main screen, oldest first.
 */
data class TerminalScreen(
    val cols: Int,
    val rows: Int,
    val grid: Array<Array<TerminalCell>>,
    val cursorRow: Int,
    val cursorCol: Int,
    val cursorVisible: Boolean,
    val reverseVideo: Boolean,
    val title: String?,
    val scrollback: List<Array<TerminalCell>>,
)

/**
 * VT100/xterm output emulator for the settings→terminal screen. Decodes the
 * pty-backed shell's escape stream into a [rows]x[cols] grid so the shell's
 * own echo, prompt, cursor, and color handling render like a real terminal.
 *
 * Only output is decoded: input is generated by the pty driver, and the
 * few queries a program makes about the terminal (DSR, DA) are answered
 * through [onTerminalResponse] so the caller can write them back into the
 * session. [append] is resumable: a sequence split at any boundary decodes
 * identically to a single call.
 *
 * @param cols columns on the grid, default 80.
 * @param rows rows on the grid, default 24.
 * @param maxScrollbackLines maximum lines retained in [TerminalScreen.scrollback].
 */
class TerminalEmulator(
    val cols: Int = 80,
    val rows: Int = 24,
    val maxScrollbackLines: Int = 2000,
) {
    /** Response sink for DSR / DA queries; the caller writes this back into the pty. */
    var onTerminalResponse: ((String) -> Unit)? = null

    /** Feed decoded terminal output; handles escape sequences split across calls. */
    fun append(text: String) {
        cachedScreen = null
        for (ch in text) process(ch)
    }

    /**
     * Current screen snapshot. Shares the backing grid arrays with the
     * emulator; invalidated on the next [append].
     */
    val screen: TerminalScreen
        get() = cachedScreen ?: TerminalScreen(
            cols = cols,
            rows = rows,
            grid = grid,
            cursorRow = cursorRow,
            cursorCol = cursorCol,
            cursorVisible = cursorVisible,
            reverseVideo = reverseVideo,
            title = title,
            scrollback = if (scrollback.isEmpty()) emptyList() else scrollback,
        ).also { cachedScreen = it }

    /** Reset to the initial state: clear grid, cursor at origin, default attrs, empty scrollback. */
    fun clear() {
        resetAll()
        cachedScreen = null
    }

    // ------------------------------------------------------------------------
    // Constants

    private companion object {
        const val GROUND = 0
        const val ESC = 1
        const val CSI = 2
        const val OSC = 3
        const val EMPTY_CHAR = ' '
        const val MAX_OSC_LEN = 4096
        const val MAX_PARAM = 65535
    }

    private val BLANK: TerminalCell = TerminalCell(EMPTY_CHAR, TerminalAttrs.DEFAULT)

    private fun blankRow(): Array<TerminalCell> = Array(cols) { BLANK }
    private fun blankGrid(): Array<Array<TerminalCell>> = Array(rows) { blankRow() }

    // ------------------------------------------------------------------------
    // Parser state (persists across append calls)

    private var state: Int = GROUND
    private val csiParams = ArrayList<Int>(16)
    private var csiDigit = 0
    private var csiDigitsSeen = false
    private var csiPrivate = false
    private val oscText = StringBuilder()

    // ------------------------------------------------------------------------
    // Grid / cursor / mode state

    private var grid: Array<Array<TerminalCell>> = blankGrid()
    private var mainGrid: Array<Array<TerminalCell>> = grid
    private var altGrid: Array<Array<TerminalCell>>? = null
    private var inAlt: Boolean = false

    private var cursorRow: Int = 0
    private var cursorCol: Int = 0
    private var pendingWrap: Boolean = false
    private var cursorVisible: Boolean = true

    private var savedRow: Int = 0
    private var savedCol: Int = 0
    private var savedAttrs: TerminalAttrs = TerminalAttrs.DEFAULT
    private var savedFullWidth: Boolean = false

    private var scrollTop: Int = 0
    private var scrollBottom: Int = rows - 1
    private var autoWrap: Boolean = true
    private var originMode: Boolean = false
    private var reverseVideo: Boolean = false

    private var attrs: TerminalAttrs = TerminalAttrs.DEFAULT
    private var title: String? = null

    private val scrollback = ArrayList<Array<TerminalCell>>()
    private val privateModes = mutableSetOf<Int>()

    private var cachedScreen: TerminalScreen? = null

    init {
        mainGrid = grid
        altGrid = blankGrid()
    }

    // ------------------------------------------------------------------------
    // State dispatch

    private fun process(ch: Char) {
        when (state) {
            GROUND -> handleGround(ch)
            ESC -> handleEsc(ch)
            CSI -> handleCsi(ch)
            OSC -> handleOsc(ch)
        }
    }

    private fun handleGround(ch: Char) {
        when (ch) {
            '\u001B' -> { state = ESC }
            '\n', '\u000B', '\u000C' -> { pendingWrap = false; index() }
            '\r' -> { cursorCol = 0; pendingWrap = false }
            '\b' -> { if (cursorCol > 0) cursorCol--; pendingWrap = false }
            '\t' -> { tab() }
            '\u0007', '\u0000' -> Unit
            else -> writeChar(ch)
        }
    }

    private fun handleEsc(ch: Char) {
        state = GROUND
        when (ch) {
            '[' -> { resetCsi(); state = CSI }
            ']' -> { oscText.setLength(0); state = OSC }
            'D' -> { pendingWrap = false; index() }
            'E' -> { pendingWrap = false; index(); cursorCol = 0 }
            'M' -> reverseIndex()
            '7' -> saveCursor()
            '8' -> restoreCursor()
            'c', 'R' -> resetAll()
            '\\', '(', ')', '*', '+', '-', '.', '/' -> Unit
            else -> { state = ESC; handleGround(ch) }
        }
    }

    private fun resetCsi() {
        csiParams.clear()
        csiDigit = 0
        csiDigitsSeen = false
        csiPrivate = false
    }

    private fun handleCsi(ch: Char) {
        when {
            ch in '0'..'9' -> {
                if (csiDigit <= 9999) {
                    csiDigit = csiDigit * 10 + (ch - '0')
                    if (csiDigit > MAX_PARAM) csiDigit = MAX_PARAM
                    csiDigitsSeen = true
                }
            }
            ch == ';' -> {
                csiParams.add(if (csiDigitsSeen) csiDigit else 0)
                csiDigit = 0
                csiDigitsSeen = false
            }
            ch == '?' -> { csiPrivate = true }
            ch == '>' -> { csiPrivate = true; csiDigit = 0; csiDigitsSeen = false }
            ch in '@'..'~' -> {
                if (csiDigitsSeen) {
                    csiParams.add(csiDigit)
                    csiDigit = 0
                    csiDigitsSeen = false
                }
                state = GROUND
                csiDispatch(ch)
            }
        }
    }

    private fun handleOsc(ch: Char) {
        when (ch) {
            '\u0007' -> { dispatchOsc(); state = GROUND }
            '\u009C' -> { dispatchOsc(); state = GROUND }
            '\u001B' -> {
                dispatchOsc()
                state = ESC
            }
            else -> { if (oscText.length < MAX_OSC_LEN) oscText.append(ch) }
        }
    }

    private fun dispatchOsc() {
        val s = oscText.toString()
        oscText.setLength(0)
        if (s.isEmpty()) return
        val sep = s.indexOf(';')
        if (sep <= 0) return
        val head = s.substring(0, sep)
        val payload = s.substring(sep + 1)
        if (payload.isEmpty()) return
        if (head == "0" || head == "2") {
            title = if (payload.length <= 256) payload else payload.substring(0, 256)
        }
    }

    private fun csiDispatch(final: Char) {
        when (final) {
            'x' -> when (csiParams.getOrNull(0) ?: 0) {
                0 -> {
                    val cur = grid[cursorRow][cursorCol]
                    grid[cursorRow][cursorCol] = TerminalCell(cur.char, TerminalAttrs.DEFAULT)
                }
                1 -> grid[cursorRow][cursorCol] = BLANK
            }
            'A' -> moveRel(-1, 0)
            'B' -> moveRel(1, 0)
            'C' -> moveRel(0, 1)
            'D' -> moveRel(0, -1)
            'H', 'f' -> {
                val r = (csiParams.getOrNull(0) ?: 1) - 1
                val c = (csiParams.getOrNull(1) ?: 1) - 1
                cursorRow = (if (originMode) r + scrollTop else r).coerceIn(scrollTop, scrollBottom)
                cursorCol = c.coerceIn(0, cols - 1)
                pendingWrap = false
            }
            'I' -> { pendingWrap = false; index() }
            'J' -> eraseDown(csiParams.getOrNull(0) ?: 0)
            'K' -> eraseLine(csiParams.getOrNull(0) ?: 0)
            'L' -> insertLines(csiParams.getOrNull(0) ?: 1)
            'M' -> deleteLines(csiParams.getOrNull(0) ?: 1)
            'P' -> deleteChars(csiParams.getOrNull(0) ?: 1)
            '@' -> insertChars(csiParams.getOrNull(0) ?: 1)
            'X' -> eraseChars(csiParams.getOrNull(0) ?: 1)
            'r' -> setScrollRegion(csiParams.getOrNull(0) ?: 1, csiParams.getOrNull(1) ?: rows)
            'm' -> applySgr()
            's' -> saveCursor()
            'u' -> restoreCursor()
            'n' -> sendDsr(csiParams.getOrNull(0) ?: 0)
            'c' -> {
                if (csiPrivate && csiDigit > 0) onTerminalResponse?.invoke("\u001B[>0;0;6;6;c")
                else onTerminalResponse?.invoke("\u001B[?62;22c")
            }
            'h' -> { if (csiPrivate) applyMode(set = true) }
            'l' -> { if (csiPrivate) applyMode(set = false) }
            't', 'q' -> Unit
        }
    }

    // ------------------------------------------------------------------------
    // Text output

    private fun writeChar(ch: Char) {
        // Handle pending deferred wrap: move to the start of the next row
        // before writing this character.
        if (pendingWrap) {
            pendingWrap = false
            if (cursorRow < rows - 1) {
                cursorRow++
                cursorCol = 0
            } else {
                scrollDown(1)
                cursorCol = 0
            }
        }

        // Wide characters occupy two columns: the char cell plus a blank
        // continuation cell.
        if (isWide(ch)) {
            if (cursorCol >= cols - 1) {
                if (autoWrap) pendingWrap = true
                return
            }
            val row = grid[cursorRow]
            row[cursorCol] = TerminalCell(ch, attrs)
            row[cursorCol + 1] = TerminalCell(EMPTY_CHAR, attrs)
            cursorCol += 2
            if (cursorCol >= cols && autoWrap) pendingWrap = true
            return
        }

        // Zero-width combining characters attach to the previous cell.
        if (isZeroWidth(ch)) {
            if (grid[cursorRow][cursorCol].char == EMPTY_CHAR) {
                grid[cursorRow][cursorCol] = TerminalCell(ch, attrs)
            }
            return
        }

        // Normal single-width character.
        grid[cursorRow][cursorCol] = TerminalCell(ch, attrs)
        if (cursorCol >= cols - 1) {
            if (autoWrap) pendingWrap = true
        } else {
            cursorCol++
        }
    }

    private fun index() {
        if (cursorRow < scrollBottom) cursorRow++
        else scrollDown(1)
    }

    private fun reverseIndex() {
        if (cursorRow > scrollTop) cursorRow--
        else scrollUp(1)
    }

    private fun tab() {
        val next = ((cursorCol / 8) + 1) * 8
        if (next >= cols) {
            if (autoWrap) { pendingWrap = false; index() }
            return
        }
        cursorCol = next
        pendingWrap = false
    }

    private fun scrollDown(count: Int) {
        val n = count.coerceIn(1, scrollBottom - scrollTop + 1)
        for (r in scrollBottom downTo scrollTop + 1) {
            val src = r - n
            grid[r] = if (src >= scrollTop) grid[src] else blankRow()
        }
        for (r in scrollTop until scrollTop + n) grid[r] = blankRow()
        if (!inAlt && scrollTop == 0) pushScrollback(grid[scrollTop])
    }

    private fun scrollUp(count: Int) {
        val n = count.coerceIn(1, scrollBottom - scrollTop + 1)
        for (r in scrollTop until scrollBottom + 1 - n) grid[r] = grid[r + n]
        for (r in scrollBottom + 1 - n until scrollBottom + 1) grid[r] = blankRow()
    }

    private fun pushScrollback(row: Array<TerminalCell>) {
        scrollback.add(row)
        while (scrollback.size > maxScrollbackLines) scrollback.removeAt(0)
    }

    // ------------------------------------------------------------------------
    // Cursor

    private fun moveRel(dRow: Int, dCol: Int) {
        cursorRow = (cursorRow + dRow).coerceIn(scrollTop, scrollBottom)
        cursorCol = (cursorCol + dCol).coerceIn(0, cols - 1)
        pendingWrap = false
    }

    private fun saveCursor() {
        savedRow = cursorRow
        savedCol = cursorCol
        savedAttrs = attrs
        savedFullWidth = cursorCol > 0 && isWide(grid[cursorRow][cursorCol - 1].char)
    }

    private fun restoreCursor() {
        cursorRow = savedRow
        cursorCol = savedCol
        attrs = savedAttrs
        if (savedFullWidth && cursorCol < cols) {
            grid[cursorRow][cursorCol] = TerminalCell(EMPTY_CHAR, attrs)
        }
        pendingWrap = false
    }

    // ------------------------------------------------------------------------
    // Erase / line/char editing

    private fun eraseLine(mode: Int) {
        val row = grid[cursorRow]
        when (mode) {
            0 -> for (c in cursorCol until cols) row[c] = BLANK
            1 -> for (c in 0..cursorCol) row[c] = BLANK
            2 -> for (c in 0 until cols) row[c] = BLANK
        }
    }

    private fun eraseChars(count: Int) {
        val row = grid[cursorRow]
        val end = minOf(cols, cursorCol + count)
        for (c in cursorCol until end) row[c] = BLANK
    }

    private fun eraseDown(mode: Int) {
        when (mode) {
            0 -> {
                val row = grid[cursorRow]
                for (c in cursorCol until cols) row[c] = BLANK
                for (r in cursorRow + 1 until rows) grid[r] = blankRow()
            }
            1 -> {
                val row = grid[cursorRow]
                for (c in 0..cursorCol) row[c] = BLANK
                for (r in 0 until cursorRow) grid[r] = blankRow()
            }
            2 -> {
                for (r in 0 until rows) grid[r] = blankRow()
                cursorRow = 0
                cursorCol = 0
            }
        }
    }

    private fun insertLines(count: Int) {
        if (cursorRow < scrollTop || cursorRow > scrollBottom) return
        val n = count.coerceIn(1, scrollBottom - cursorRow + 1)
        for (r in scrollBottom downTo cursorRow + 1) {
            grid[r] = if (r - n >= cursorRow) grid[r - n] else blankRow()
        }
        for (r in cursorRow until cursorRow + n) grid[r] = blankRow()
    }

    private fun deleteLines(count: Int) {
        if (cursorRow < scrollTop || cursorRow > scrollBottom) return
        val n = count.coerceIn(1, scrollBottom - cursorRow + 1)
        for (r in cursorRow until scrollBottom + 1 - n) grid[r] = grid[r + n]
        for (r in scrollBottom + 1 - n until scrollBottom + 1) grid[r] = blankRow()
    }

    private fun insertChars(count: Int) {
        val n = count.coerceIn(1, cols - cursorCol)
        val row = grid[cursorRow]
        for (c in cols - 1 downTo cursorCol + n) row[c] = row[c - n]
        for (c in cursorCol until cursorCol + n) row[c] = BLANK
    }

    private fun deleteChars(count: Int) {
        val n = count.coerceIn(1, cols - cursorCol)
        val row = grid[cursorRow]
        for (c in cursorCol until cols - n) row[c] = row[c + n]
        for (c in cols - n until cols) row[c] = BLANK
    }

    // ------------------------------------------------------------------------
    // Modes

    private fun setScrollRegion(top1: Int, bot1: Int) {
        val t = (top1 - 1).coerceIn(0, rows - 1)
        val b = (bot1 - 1).coerceIn(0, rows - 1)
        if (t >= b) return
        scrollTop = t
        scrollBottom = b
        cursorRow = t
        cursorCol = 0
        pendingWrap = false
    }

    private fun applyMode(set: Boolean) {
        for (p in csiParams) {
            when (p) {
                1, 3, 12, 44, 1036, 1048, 1010, 2004 -> {
                    if (set) privateModes.add(p) else privateModes.remove(p)
                }
                5 -> {
                    reverseVideo = set
                    if (set) privateModes.add(p) else privateModes.remove(p)
                }
                6 -> {
                    originMode = set
                    if (set) { cursorRow = scrollTop; cursorCol = 0; privateModes.add(p) }
                    else { cursorRow = 0; cursorCol = 0; privateModes.remove(p) }
                }
                7 -> {
                    autoWrap = set
                    if (set) privateModes.add(p) else privateModes.remove(p)
                }
                25 -> {
                    cursorVisible = set
                    if (set) privateModes.add(p) else privateModes.remove(p)
                }
                47, 1047 -> { if (set) enterAlt(p) else leaveAlt(p) }
                1049 -> { if (set) enterAlt(p) else leaveAlt(p) }
            }
        }
    }

    private fun enterAlt(mode: Int) {
        if (inAlt) return
        if (mode == 1049) saveCursor()
        grid = altGrid ?: blankGrid()
        if (mode == 1049) {
            for (r in 0 until rows) grid[r] = blankRow()
        }
        inAlt = true
        cursorRow = 0
        cursorCol = 0
        pendingWrap = false
    }

    private fun leaveAlt(mode: Int) {
        if (!inAlt) return
        val cur = grid
        grid = mainGrid
        altGrid = cur
        inAlt = false
        if (mode == 1049) restoreCursor()
    }

    private fun sendDsr(n: Int) {
        val response = when (n) {
            5 -> "\u001B[0n"
            6 -> "\u001B[${cursorRow + 1};${cursorCol + 1}R"
            else -> return
        }
        onTerminalResponse?.invoke(response)
    }

    private fun resetAll() {
        val newGrid = blankGrid()
        grid = newGrid
        mainGrid = newGrid
        altGrid = blankGrid()
        inAlt = false
        cursorRow = 0
        cursorCol = 0
        cursorVisible = true
        reverseVideo = false
        originMode = false
        autoWrap = true
        scrollTop = 0
        scrollBottom = rows - 1
        pendingWrap = false
        attrs = TerminalAttrs.DEFAULT
        title = null
        state = GROUND
        privateModes.clear()
        savedRow = 0
        savedCol = 0
        savedAttrs = TerminalAttrs.DEFAULT
        savedFullWidth = false
        csiParams.clear()
        csiDigit = 0
        csiDigitsSeen = false
        csiPrivate = false
        oscText.setLength(0)
    }

    // ------------------------------------------------------------------------
    // SGR (CSI ... m)

    private fun applySgr() {
        if (csiParams.isEmpty()) {
            attrs = TerminalAttrs.DEFAULT
            return
        }
        val p = csiParams
        var i = 0
        while (i < p.size) {
            val v = p[i]
            when (v) {
                0 -> attrs = TerminalAttrs.DEFAULT
                1 -> if (!attrs.bold) attrs = attrs.copy(bold = true)
                2 -> if (!attrs.dim) attrs = attrs.copy(dim = true)
                3 -> if (!attrs.italic) attrs = attrs.copy(italic = true)
                4 -> if (!attrs.underline) attrs = attrs.copy(underline = true)
                5 -> if (!attrs.blink) attrs = attrs.copy(blink = true)
                7 -> if (!attrs.inverse) attrs = attrs.copy(inverse = true)
                8 -> if (!attrs.hide) attrs = attrs.copy(hide = true)
                9 -> if (!attrs.strike) attrs = attrs.copy(strike = true)
                21 -> if (!attrs.underline) attrs = attrs.copy(underline = true)
                22 -> if (attrs.bold || attrs.dim) attrs = attrs.copy(bold = false, dim = false)
                23 -> if (attrs.italic) attrs = attrs.copy(italic = false)
                24 -> if (attrs.underline) attrs = attrs.copy(underline = false)
                25 -> if (attrs.blink) attrs = attrs.copy(blink = false)
                27 -> if (attrs.inverse) attrs = attrs.copy(inverse = false)
                28 -> if (attrs.hide) attrs = attrs.copy(hide = false)
                29 -> if (attrs.strike) attrs = attrs.copy(strike = false)
                39 -> if (attrs.fg !== TerminalColor.Default) attrs = attrs.copy(fg = TerminalColor.Default)
                49 -> if (attrs.bg !== TerminalColor.Default) attrs = attrs.copy(bg = TerminalColor.Default)
                38, 48, 58, 68 -> {
                    val isFg = (v == 38 || v == 58)
                    if (i + 1 < p.size) {
                        when (p[i + 1]) {
                            5 -> if (i + 2 < p.size) {
                                val col = TerminalColor.Index(p[i + 2].coerceIn(0, 255))
                                attrs = if (isFg) attrs.copy(fg = col) else attrs.copy(bg = col)
                                i += 2
                            }
                            2 -> if (i + 4 < p.size) {
                                val col = TerminalColor.Truecolor(
                                    p[i + 2].coerceIn(0, 255),
                                    p[i + 3].coerceIn(0, 255),
                                    p[i + 4].coerceIn(0, 255),
                                )
                                attrs = if (isFg) attrs.copy(fg = col) else attrs.copy(bg = col)
                                i += 4
                            }
                        }
                    }
                }
                in 30..37 -> attrs = attrs.copy(fg = TerminalColor.Index(v - 30))
                in 40..47 -> attrs = attrs.copy(bg = TerminalColor.Index(v - 40))
                in 90..97 -> attrs = attrs.copy(fg = TerminalColor.Index(v - 90 + 8))
                99 -> if (attrs.fg !== TerminalColor.Default) attrs = attrs.copy(fg = TerminalColor.Default)
                in 100..107 -> attrs = attrs.copy(bg = TerminalColor.Index(v - 100 + 8))
                109 -> if (attrs.bg !== TerminalColor.Default) attrs = attrs.copy(bg = TerminalColor.Default)
            }
            i++
        }
    }

    // ------------------------------------------------------------------------
    // Character classification

    private fun isZeroWidth(ch: Char): Boolean {
        val cp = ch.code
        return (cp in 0x0300..0x036F) || cp == 0x200B || (cp in 0xFE20..0xFE2F)
    }

    private fun isWide(ch: Char): Boolean {
        val cp = ch.code
        return (cp in 0x1100..0x115F) ||
            (cp in 0x2E80..0x303E) ||
            (cp in 0x3041..0x33FF) ||
            (cp in 0x3400..0x4DBF) ||
            (cp in 0x4E00..0x9FFF) ||
            (cp in 0xA000..0xA4CF) ||
            (cp in 0xAC00..0xD7A3) ||
            (cp in 0xF900..0xFAFF) ||
            (cp in 0xFE30..0xFE6F) ||
            (cp in 0xFF00..0xFF60) ||
            (cp in 0xFFE0..0xFFE6) ||
            (cp in 0x1F300..0x1F64F) ||
            (cp in 0x1F900..0x1F9FF) ||
            (cp >= 0x20000 && cp <= 0x3FFFD)
    }
}
