/*
 * Copyright 2026 ECSDevs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@file:Suppress("DEPRECATION", "OPT_IN_USAGE", "UnstableApiUsage")

import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
}

// The app version is one scheme for every client: the semantic version in the
// repository-root VERSION file (rootProject.ext["versionName"]) plus the git
// commit count (rootProject.ext["versionCode"]) — see the root build script.
//
// Android reads both back from the installed package (PackageManager), but
// Desktop and Web have no package registry to query, so the two values are
// baked into a generated Kotlin constant they compile against. Callers
// therefore see the same version string on every platform.
val appVersionName = rootProject.ext["versionName"] as String
val appVersionCode = rootProject.ext["versionCode"] as Int

/**
 * Writes the version constants for the compiled-against-a-constant targets.
 *
 * A typed task with declared inputs/outputs rather than an ad-hoc `doLast`:
 * `commonMain` registers its output DIRECTORY as a source root, and Gradle only
 * infers the task dependency from a task's own output property (see the
 * `kotlin.srcDir` call below). Both the directory and the file are declared —
 * the directory because KSP and the Kotlin compiler need a directory source
 * root (a file source root fails with "Source directory … is not a directory"),
 * the file because that is the actual tracked artifact.
 */
abstract class GenerateAppVersion : DefaultTask() {
    @get:Input abstract val versionName: Property<String>
    @get:Input abstract val versionCode: Property<Int>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty
    @get:OutputFile abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        // Rewrite only on change: the file is a compile input, so touching its
        // timestamp would re-run the Kotlin compile in incremental builds.
        val text = """
            |// Generated by the ':shared:generateAppVersion' Gradle task — do not edit.
            |package cc.ptoe.messenger.presentation.platform
            |
            |/** Semantic version name from the repository-root VERSION file. */
            |internal const val APP_VERSION_NAME = "${versionName.get()}"
            |
            |/** Version code: the git commit count this build was made from. */
            |internal const val APP_VERSION_CODE = ${versionCode.get()}
            |
        """.trimMargin()
        if (!file.isFile || file.readText() != text) {
            file.writeText(text)
        }
    }
}

val generateAppVersion by tasks.registering(GenerateAppVersion::class) {
    versionName.set(appVersionName)
    versionCode.set(appVersionCode)
    // The package directory is the source root; the .kt file inside it is the
    // tracked artifact. `kotlin.srcDir(provider)` below passes the DIRECTORY,
    // because a file source root breaks KSP ("not a directory").
    val packageDir = layout.buildDirectory.dir(
        "generated/appVersion/cc/ptoe/messenger/presentation/platform"
    )
    outputDir.set(packageDir)
    outputFile.set(packageDir.map { it.file("AppVersion.kt") })
}

kotlin {
    androidLibrary {
        namespace = "cc.ptoe.messenger.shared"
        compileSdk {
            version = release(37)
        }
        minSdk = 30
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
        androidResources { enable = true }

        // Run commonTest on the Android (JVM) host target as well; silences the
        // "commonTest source directory exists, but android host tests are not enabled" warning.
        withHostTest { }
    }

    jvm("desktop")

    // Compose Multiplatform web target. The browser bundle's entry point lives in
    // :webApp (which calls `binaries.executable()`); this library target only needs
    // to compile, so no executable binary is declared here.
    wasmJs {
        browser()
        compilerOptions { freeCompilerArgs.add("-Xexpect-actual-classes") }
    }

    sourceSets {
        // Shared by Android + Desktop but NOT wasmJs: Room, DataStore-with-okio-paths,
        // okio's FileSystem.SYSTEM and the Room-backed repositories all live here.
        val jvmSharedMain by creating { dependsOn(getByName("commonMain")) }

        // Shared Android + Desktop tests. They are NOT in commonTest on
        // purpose: they use org.junit + runBlocking, which do not exist on
        // wasmJs, and a commonTest directory would force a wasmJs test
        // compilation of them.
        val jvmSharedTest by creating { dependsOn(getByName("commonTest")) }

        getByName("commonMain") {
            // Generated APP_VERSION_NAME / APP_VERSION_CODE (see above).
            //
            // Pass the TASK's output DIRECTORY provider, not its resolved value:
            // Gradle infers the dependency from a task-backed source root, so
            // every compilation including commonMain runs the generator first.
            // An explicit name-based `tasks.matching { … }.dependsOn(...)` rule
            // was tried first and silently matched nothing — the real compile
            // tasks are `compileKotlinDesktop` / `compileKotlinWasmJs` /
            // `compileKotlinMetadata`, none of which end in "Kotlin", so CI
            // failed with "Unresolved reference: APP_VERSION_NAME" while a warm
            // local build passed on the stale generated file.
            kotlin.srcDir(generateAppVersion.flatMap { it.outputDir })
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(libs.jetbrains.compose.material3)
                implementation(compose.materialIconsExtended)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(compose.components.uiToolingPreview)

                implementation(libs.kotlinx.coroutines.core)

                implementation(libs.androidx.datastore.preferences.core)
                implementation(libs.androidx.datastore.core.okio)

                implementation(libs.jetbrains.navigation.compose)
                implementation(libs.jetbrains.lifecycle.viewmodel.compose)
                implementation(libs.jetbrains.lifecycle.runtime.compose)

                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.ktor.client.logging)
                implementation(libs.kotlinx.serialization.json)

                implementation(libs.coil3.compose)
                implementation(libs.coil3.network.ktor3)

                implementation(libs.kotlinx.datetime)
                implementation(libs.okio)
            }
        }

        getByName("androidMain") {
            dependsOn(jvmSharedMain)
            dependencies {
                implementation(project(":core-bindings"))
                implementation(project(":renderer-android"))
                implementation(libs.androidx.recyclerview)
                implementation(compose.preview)
                implementation(libs.androidx.activity.compose)
                implementation(libs.androidx.core.ktx)
                implementation(libs.kotlinx.coroutines.android)
                implementation(libs.ktor.client.okhttp)
                implementation(libs.okhttp)

                implementation(libs.java.websocket)

                implementation(libs.ucrop)
                implementation(libs.androidx.exifinterface)
                implementation(libs.androidx.appcompat)
                implementation(libs.androidx.transition)
            }
        }

        getByName("desktopTest") { dependsOn(jvmSharedTest) }

        getByName("desktopMain") {
            dependsOn(jvmSharedMain)
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.ktor.client.okhttp)
            }
        }

        // Room + bundled SQLite: JVM/native only (no wasmJs artifact exists).
        getByName("jvmSharedMain") {
            dependencies {
                implementation(libs.androidx.room.runtime)
                implementation(libs.androidx.sqlite.bundled)
            }
        }

        getByName("wasmJsMain") {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.ui)
                implementation(compose.materialIconsExtended)
                implementation(compose.components.resources)
                implementation(libs.jetbrains.compose.material3)

                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.js)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.ktor.client.logging)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.datetime)
                implementation(libs.okio)
                implementation(libs.kotlinx.browser)

                implementation(libs.coil3.compose)
                implementation(libs.coil3.network.ktor3)

                implementation(libs.jetbrains.navigation.compose)
                implementation(libs.jetbrains.lifecycle.viewmodel.compose)
                implementation(libs.jetbrains.lifecycle.runtime.compose)
            }
        }

        getByName("desktopTest") {
            dependencies {
                @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
                implementation(compose.uiTest)
                implementation(kotlin("test"))
            }
        }

        jvmSharedTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

// Compose 1.12 gates wasmJs tests behind a check that requires
// `binaries.executable()` so the Skiko runtime can be bundled by webpack. It
// fires here because wasmJsMain depends on Compose UI, but this module is a
// LIBRARY with no wasmJs test sources at all — the shared tests live in
// jvmSharedTest, which never compiles for wasm. Declaring an executable binary
// on a library target would be wrong (the web entry point belongs to :webApp),
// so the inapplicable check is disabled instead.
tasks.matching { it.name == "checkComposeUiTestConfigurationForWasmJs" }.configureEach {
    enabled = false
}

compose.resources {
    packageOfResClass = "cc.ptoe.messenger.generated.resources"
    generateResClass = always
}

dependencies {
    // Room compiler: per-target KSP registration (AGP 9 KMP library plugin pattern).
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspDesktop", libs.androidx.room.compiler)
}
